spring:
  application:
    name: mall
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret:
    key: ${SECRET_KEY}
  expiration: 3600000